import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center items-center
                        min-h-screen bg-gray-100`}>
        <div className = "w-[375px] h-[812px] bg-white shadow-lg border-gray-200">
            {children}
        </div>
      </body>
    </html>
  );
}
